install:
- ps: |
    $destPath = "$env:SYSTEMDRIVE\Tools\PsTools"
    if(Test-Path $destPath) {
        del $destPath -Recurse -Force
    }

    $zipPath = "$env:TEMP\PSTools.zip"
    (New-Object Net.WebClient).DownloadFile('https://download.sysinternals.com/files/PSTools.zip', $zipPath)

    7z x $zipPath -o"$destPath" | Out-Null

build_script:
  - PowerShell -Command %APPVEYOR_BUILD_FOLDER%\hello.ps1

test_script:
  - psexec.exe -s -accepteula PowerShell -ExecutionPolicy ByPass -Command %APPVEYOR_BUILD_FOLDER%\hello.ps1
